# Written by Khoi Van

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Update RSS feed

# on:
#   pull_request:
#     branches: [ master ]
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'
  push:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run execute.py
      run: |
        python execute.py
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        # git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --global --add safe.directory /github/workspace
        git commit -m "ci: Automated update $(date)" -a | exit 0
        # git commit -m "ci: Automated update $(date)" -a
        # git show --name-only HEAD
    - name: Push changes
#       if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@v0.5.0
#       uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
